spring:
  application:
    name: todo-app
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: user_prueba # INDICAR TU ESQUEMA / USUARIO
    password: 1234 # PASSWORD DE TU ESQUEMA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true